#!/usr/bin/env python3
"""
Management script for the MI Lab resource management project.

This file mimics the manage.py script that is generated by the Django
startproject command. It serves as the command-line entry point for
administrative tasks such as running the development server, applying
migrations, creating superusers and running tests. Keeping this file in
the repository makes it simple for downstream developers to get started
without needing to install additional scaffolding tools.
"""
import os
import sys


def main() -> None:
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mi_lab.settings')
    try:
        from django.core.management import execute_from_command_line  # type: ignore
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()