# Generated by Django 6.0.1 on 2026-01-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_end_after_start',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gte', models.F('start_time'))), name='booking_end_after_start'),
        ),
    ]
