# Generated by Django 6.0.1 on 2026-01-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0002_remove_booking_booking_end_after_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
