# Generated by Django 6.0.1 on 2026-03-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0004_booking_created_by_booking_project_name_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
