# Generated by Django 6.0.1 on 2026-04-15 07:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0005_registrationrequest_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='software',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='computer_code',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='gpu',
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('PC', 'PC'), ('RUNPOD', 'RunPod')], default='PC', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RA', 'Research Assistant'), ('Student', 'Student'), ('Intern', 'Intern'), ('Faculty', 'Faculty')], default='RA', max_length=10),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('grant', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('PROPOSED', 'Proposed'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='PROPOSED', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimated_budget_bdt', models.BigIntegerField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True, verbose_name='Estimated Completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('co_principal_investigators', models.ManyToManyField(blank=True, related_name='co_pi_projects', to=settings.AUTH_USER_MODEL)),
                ('principal_investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_projects', to=settings.AUTH_USER_MODEL)),
                ('research_assistants', models.ManyToManyField(blank=True, related_name='ra_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('RA', 'Research Assistant'), ('Student', 'Student'), ('Intern', 'Intern'), ('Faculty', 'Faculty')], default='RA', max_length=10)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
