# Generated by Django 6.0.1 on 2026-04-16 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0006_remove_booking_software_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or description'),
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('overleaf', 'Overleaf'), ('google_doc', 'Google Doc'), ('drive', 'Google Drive'), ('notion', 'Notion'), ('github', 'GitHub'), ('other', 'Other')], default='other', max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(blank=True, help_text='Optional display label', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_links', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='labapp.project')),
            ],
            options={
                'ordering': ['platform', 'id'],
            },
        ),
    ]
