# Generated by Django 6.0.6 on 2026-07-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0007_v3_profile_links_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='True once the invitation email was delivered successfully.'),
        ),
    ]
