# Generated by Django 6.0.6 on 2026-07-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0008_userinvitation_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_announcements',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen_weekly_updates',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
